version: "3"

services:
  app:
    container_name: nodejs-apollo-docker
    restart: always
    build: .
    ports:
      - 8080:4000
    links:
      - db
    volumes:
      - ./src:/usr/src/app/src

  db:
    container_name: mongo-database
    image: mongo
    restart: always
    ports:
      - 27017:27017
