version: "3"

services:
  app:
    container_name: nodejs-apollo-docker
    restart: always
    build: .
    ports:
      - 8080:4000
    links:
      - db

  db:
    container_name: mongo-database
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
